name: Build LaTeX templates
on: 
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * 1' #Â Run at 0400 every Monday.
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile Letter
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_letter.tex
            latexmk_use_xelatex: true
      - name: Compile Portrait Poster
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_poster_portrait.tex
            latexmk_use_xelatex: true
      - name: Compile Landscape Poster
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_poster_landscape.tex
            latexmk_use_xelatex: true
      - name: Compile Presentation
        uses: xu-cheng/latex-action@v3
        with:
            root_file: template_presentation.tex
            latexmk_use_xelatex: true
      - name: Upload PDFs
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
            name: PDF
            path: '*.pdf'